# Generated by Django 5.0.7 on 2026-06-01 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=160, unique=True)),
                ('transcript', models.TextField(blank=True)),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-consultation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_identifier', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anaemia', models.CharField(blank=True, max_length=255)),
                ('jaundice', models.CharField(blank=True, max_length=255)),
                ('cyanosis', models.CharField(blank=True, max_length=255)),
                ('edema', models.CharField(blank=True, max_length=255)),
                ('systemic_examination_notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_exam', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ChiefComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_complaints', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(blank=True, max_length=255)),
                ('diagnosis_note', models.CharField(blank=True, max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='HealthScreening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=120)),
                ('pulse_rate', models.CharField(blank=True, max_length=120)),
                ('temperature', models.CharField(blank=True, max_length=120)),
                ('respiratory_rate', models.CharField(blank=True, max_length=120)),
                ('weight', models.CharField(blank=True, max_length=120)),
                ('height', models.CharField(blank=True, max_length=120)),
                ('bmi', models.CharField(blank=True, max_length=120)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_screening', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_name', models.CharField(blank=True, max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('instruction', models.CharField(blank=True, max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clinical.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='GynaeObsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lmp', models.DateField(blank=True, null=True)),
                ('edd', models.DateField(blank=True, null=True)),
                ('para', models.CharField(blank=True, max_length=255)),
                ('gravida', models.CharField(blank=True, max_length=255)),
                ('alc', models.CharField(blank=True, max_length=255)),
                ('delivery_history', models.CharField(blank=True, max_length=255)),
                ('contraceptives_history', models.CharField(blank=True, max_length=255)),
                ('pv_examination', models.CharField(blank=True, max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gynae_obs_history', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father', models.CharField(blank=True, max_length=255)),
                ('mother', models.CharField(blank=True, max_length=255)),
                ('siblings', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='clinical.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinical.patient'),
        ),
        migrations.CreateModel(
            name='AllergicHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food', models.CharField(blank=True, max_length=255)),
                ('medicine', models.CharField(blank=True, max_length=255)),
                ('pollen', models.CharField(blank=True, max_length=255)),
                ('dust', models.CharField(blank=True, max_length=255)),
                ('mites', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergic_history', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smoking', models.CharField(blank=True, max_length=255)),
                ('alcohol', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.CharField(blank=True, max_length=255)),
                ('food_preferences', models.CharField(blank=True, max_length=255)),
                ('others', models.CharField(blank=True, max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_history', to='clinical.patient')),
            ],
        ),
    ]
